/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalTeacherRouteImport } from './routes/portal.teacher'
import { Route as PortalSuperadminRouteImport } from './routes/portal.superadmin'
import { Route as PortalStudentRouteImport } from './routes/portal.student'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalParentRouteImport } from './routes/portal.parent'
import { Route as PortalAlumniRouteImport } from './routes/portal.alumni'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as PortalMKeyRouteImport } from './routes/portal.m.$key'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTeacherRoute = PortalTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSuperadminRoute = PortalSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalParentRoute = PortalParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAlumniRoute = PortalAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMKeyRoute = PortalMKeyRouteImport.update({
  id: '/m/$key',
  path: '/m/$key',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/superadmin': typeof PortalSuperadminRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/m/$key': typeof PortalMKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/superadmin': typeof PortalSuperadminRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/portal': typeof PortalIndexRoute
  '/portal/m/$key': typeof PortalMKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/get-involved': typeof GetInvolvedRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/stories': typeof StoriesRoute
  '/team': typeof TeamRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/alumni': typeof PortalAlumniRoute
  '/portal/parent': typeof PortalParentRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/student': typeof PortalStudentRoute
  '/portal/superadmin': typeof PortalSuperadminRoute
  '/portal/teacher': typeof PortalTeacherRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/m/$key': typeof PortalMKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/get-involved'
    | '/login'
    | '/portal'
    | '/projects'
    | '/stories'
    | '/team'
    | '/portal/admin'
    | '/portal/alumni'
    | '/portal/parent'
    | '/portal/profile'
    | '/portal/student'
    | '/portal/superadmin'
    | '/portal/teacher'
    | '/portal/'
    | '/portal/m/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/get-involved'
    | '/login'
    | '/projects'
    | '/stories'
    | '/team'
    | '/portal/admin'
    | '/portal/alumni'
    | '/portal/parent'
    | '/portal/profile'
    | '/portal/student'
    | '/portal/superadmin'
    | '/portal/teacher'
    | '/portal'
    | '/portal/m/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/get-involved'
    | '/login'
    | '/portal'
    | '/projects'
    | '/stories'
    | '/team'
    | '/portal/admin'
    | '/portal/alumni'
    | '/portal/parent'
    | '/portal/profile'
    | '/portal/student'
    | '/portal/superadmin'
    | '/portal/teacher'
    | '/portal/'
    | '/portal/m/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  StoriesRoute: typeof StoriesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/teacher': {
      id: '/portal/teacher'
      path: '/teacher'
      fullPath: '/portal/teacher'
      preLoaderRoute: typeof PortalTeacherRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/superadmin': {
      id: '/portal/superadmin'
      path: '/superadmin'
      fullPath: '/portal/superadmin'
      preLoaderRoute: typeof PortalSuperadminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/parent': {
      id: '/portal/parent'
      path: '/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof PortalParentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/alumni': {
      id: '/portal/alumni'
      path: '/alumni'
      fullPath: '/portal/alumni'
      preLoaderRoute: typeof PortalAlumniRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/m/$key': {
      id: '/portal/m/$key'
      path: '/m/$key'
      fullPath: '/portal/m/$key'
      preLoaderRoute: typeof PortalMKeyRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalAlumniRoute: typeof PortalAlumniRoute
  PortalParentRoute: typeof PortalParentRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalStudentRoute: typeof PortalStudentRoute
  PortalSuperadminRoute: typeof PortalSuperadminRoute
  PortalTeacherRoute: typeof PortalTeacherRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalMKeyRoute: typeof PortalMKeyRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalAlumniRoute: PortalAlumniRoute,
  PortalParentRoute: PortalParentRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalStudentRoute: PortalStudentRoute,
  PortalSuperadminRoute: PortalSuperadminRoute,
  PortalTeacherRoute: PortalTeacherRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalMKeyRoute: PortalMKeyRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  StoriesRoute: StoriesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
